esphome:
  name: "r48xx-off-grid"
  friendly_name: "R48xx-off-grid"

  on_boot:

    - priority: 600
      then:
        - delay: 15s
        - script.execute: setup_sequence

    - priority: 800
      then:
        - delay: 3s
        - text.set: { id: t_broker, value: !lambda 'return id(g_broker).c_str();' }
        - text.set: { id: t_user,   value: !lambda 'return id(g_user).c_str();' }
        - text.set: { id: t_pass,   value: !lambda 'return id(g_pass).c_str();' }
        - text.set: { id: t_port,   value: !lambda 'return std::to_string(id(g_port));' }

    - priority: 900
      then:
        - delay: 6s
        - wait_until:             # make sure Wi-Fi is ready first
            condition: wifi.connected
            timeout: 20s
        - if:
            condition:
              lambda: |-
                return !id(g_broker).empty()      &&
                       id(g_port) > 0;
            then:
              - logger.log:
                  tag: "config"
                  level: INFO
                  format: "All MQTT credentials look good – auto-connecting…"
              - script.execute: mqtt_reconnect
            else:
              - logger.log:
                  tag: "config"
                  level: INFO
                  format: "MQTT credentials incomplete – skipping auto-connect"
      



packages:
  - url: https://github.com/LocoSlug/CAN-BUS-control-R4875G1-with-ESPHome-and-MQTT
    ref: mqttreceive
    refresh: 0s
    files:
      - path: 'packages/core.yaml'
      - path: 'packages/mqtt.yaml'
      - path: 'packages/globals.yaml'
      - path: 'packages/scripts.yaml'
      - path: 'packages/canbus.yaml'
      - path: 'packages/sensors.yaml'
      - path: 'packages/controls.yaml'
      - path: 'packages/intervals.yaml'
